#write a program to store seven fruits in a list entered by user
fruits = []
f1 = input("Enter Fruit name1 : ")
fruits.append(f1)
f2 = input("Enter Fruit name2 : ")
fruits.append(f2)
f3 = input("Enter Fruit name3 : ")
fruits.append(f3)
f4 = input("Enter Fruit name4 : ")
fruits.append(f4)
f5 = input("Enter Fruit name5 : ")
fruits.append(f5)
f6 = input("Enter Fruit name6 : ")
fruits.append(f6)
f7 = input("Enter Fruit name7 : ")
fruits.append(f7)
print(fruits)
