# write a program to input eight numbers from the user and display all the unique number (once).
numbers = []
number1= int(input("Enter a number"))
numbers.append(number1)
number2= int(input("Enter a number"))
numbers.append(number2)
number3= int(input("Enter a number"))
numbers.append(number3)
number4= int(input("Enter a number"))
numbers.append(number4)
number5= int(input("Enter a number"))
numbers.append(number5)
number6= int(input("Enter a number"))
numbers.append(number6)
number7= int(input("Enter a number"))
numbers.append(number7)
number8= int(input("Enter a number"))
numbers.append(number8)
print("unique numbers", set(numbers))